#!/bin/bash

SCHEMA=1_Create_Database_Structure.sql
VIEWS=2_Create_Views_StoredProcedures.sql
DATA=3_Insert_TestData_v2.sql

echo "Hola!  This script will import all the data into the prism DB on your local machine."
echo "We're assuming you have root permissions to your local mysql instance, and that the instance is running on port 3306."
echo "If your mysql is NOT running on port 3306, the script will give an error.  NEVER FEAR..."
echo "Simply run the script again with a single argument -- the port your mysql server is running on."
echo
echo "You'll get 3 distinct password prompts for each of the sql files that are imported.  Simply put in your password and press enter."

if [[ $# != 0 ]] ; then
  PORT=$1
else
  PORT=3306
fi

if [[ ! -e $SCHEMA || ! -e $VIEWS || ! -e $DATA ]] ; then
  echo "Either you're missing the .sql files we need, or their names have changed.  womp womp"
fi

echo $PORT

mysql -u root -p mysql -h 127.0.0.1 --port $PORT < $SCHEMA
mysql -u root -p mysql -h 127.0.0.1 --port $PORT < $VIEWS
mysql -u root -p prism -h 127.0.0.1 --port $PORT < $DATA

if [[ $? == 0 ]] ; then
  echo "SUCCESS"
else 
  echo "Something has gone wrong.  Sorry boo."
fi
